name: profile
description: "BinaryLurkerex Profile Project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7

dev_dependencies:
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
